"""create table File

Revision ID: 72406c8305a2
Revises: 
Create Date: 2020-02-04 14:15:15.201118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72406c8305a2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('filepath', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_filepath'), 'file', ['filepath'], unique=False)
    op.create_index(op.f('ix_file_name'), 'file', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_name'), table_name='file')
    op.drop_index(op.f('ix_file_filepath'), table_name='file')
    op.drop_table('file')
    # ### end Alembic commands ###
